# Generated by Django 6.0.1 on 2026-02-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
