# Generated by Django 6.0.1 on 2026-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_start_time_task_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_offset_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
