# Generated by Django 6.0.1 on 2026-02-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_task_reminder_offset_minutes_task_reminder_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_offset_minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reminder_sent_at',
        ),
    ]
