# Generated by Django 6.0.1 on 2026-02-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_tasknote_taskresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_notes/'),
        ),
    ]
