# Generated by Django 6.0.1 on 2026-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_tasknote_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasknote',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
